### ISSUE TITLE
Use LocalStorage in order to save configurations

### ISSUE THREAD

**Issue by artemyarulin** [LinogeFly/Scripts#1]
:+1:

**Comment by LinogeFly** [comment]
Yeah yeah, I know. It's just a draft version :)

**Comment by LinogeFly** [comment]
Done! :)

Well, technically I use Greasemonkey wrapper functions for now in order to save configuration in LocalStorage, But dependency on Greasemonkey API is another story :)

**Comment by artemyarulin** [comment]
:+1:
