### ISSUE TITLE
А Хде Ридми???

### ISSUE THREAD

**Issue by artemyarulin** [LinogeFly/Scripts#3]
![Where?](http://fc09.deviantart.net/fs71/i/2010/204/7/c/my_cat_looks_at_you_by_Ireland_fox.jpg)

**Comment by LinogeFly** [comment]
:D
Все будет! 
З.Ы. Спасибо еще раз за помощь с настройкой, прикольно блин! :)

**Comment by artemyarulin** [comment]
Ну окай, пока прощаю :)
